//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newsie {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newsie.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing for more.
        /// </summary>
        internal static string BingForMore {
            get {
                return ResourceManager.GetString("BingForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm... I did not understand that. Rephrase your message and try again..
        /// </summary>
        internal static string FallbackIntentMessage {
            get {
                return ResourceManager.GetString("FallbackIntentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Story.
        /// </summary>
        internal static string FullStoryString {
            get {
                return ResourceManager.GetString("FullStoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! What would you like to read about? You can either pick a category below or just type the topic. I&apos;ll do my best to fetch the latest and the most important stories from across the web, powered by Bing News..
        /// </summary>
        internal static string GreetOnDemand {
            get {
                return ResourceManager.GetString("GreetOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll pull in some news about {0} category!.
        /// </summary>
        internal static string NewsCategoryTypeMessage {
            get {
                return ResourceManager.GetString("NewsCategoryTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you go..
        /// </summary>
        internal static string NewsTopicTypeMessage {
            get {
                return ResourceManager.GetString("NewsTopicTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        internal static string PluralHourAgo {
            get {
                return ResourceManager.GetString("PluralHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins ago.
        /// </summary>
        internal static string PluralMinAgo {
            get {
                return ResourceManager.GetString("PluralMinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read summary.
        /// </summary>
        internal static string ReadSummary {
            get {
                return ResourceManager.GetString("ReadSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour ago.
        /// </summary>
        internal static string SingleHourAgo {
            get {
                return ResourceManager.GetString("SingleHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min ago.
        /// </summary>
        internal static string SingleMinAgo {
            get {
                return ResourceManager.GetString("SingleMinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, I&apos;m sorry. I could not summarize the article..
        /// </summary>
        internal static string SummaryErrorMessage {
            get {
                return ResourceManager.GetString("SummaryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY.
        /// </summary>
        internal static string SummaryString {
            get {
                return ResourceManager.GetString("SummaryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold on! I&apos;ll be back in a jiffy!.
        /// </summary>
        internal static string SummaryWaitMessage {
            get {
                return ResourceManager.GetString("SummaryWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on web.
        /// </summary>
        internal static string ViewOnWeb {
            get {
                return ResourceManager.GetString("ViewOnWeb", resourceCulture);
            }
        }
    }
}
