/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from '@azure/ms-rest-js';
import * as Models from '../schema/models';
import * as Mappers from '../schema/models/mappers';
import * as operations from '../schema/operations';
import { TeamsConnectorClientContext } from './teamsConnectorClientContext';

class TeamsConnectorClient extends TeamsConnectorClientContext {
  // Operation groups
  teams: operations.Teams;

  /**
   * Initializes a new instance of the TeamsConnectorClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.TeamsConnectorClientOptions) {
    super(credentials, options);
    this.teams = new operations.Teams(this);
  }
}

// Operation Specifications

export {
  TeamsConnectorClient,
  TeamsConnectorClientContext,
  Models as TeamsConnectorModels,
  Mappers as TeamsConnectorMappers
};
export * from '../schema/operations';
