/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from '@azure/ms-rest-js';
import * as Models from '../schema/models';

export class TeamsConnectorClientContext extends msRest.ServiceClient {
  credentials: msRest.ServiceClientCredentials;

  /**
   * Initializes a new instance of the TeamsConnectorClientContext class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.TeamsConnectorClientOptions) {

    if (!options) {
      options = {};
    }

    super(credentials, options);

    this.baseUri = options.baseUri || this.baseUri || 'https://api.botframework.com';
    this.requestContentType = 'application/json; charset=utf-8';
    this.credentials = credentials;
  }
}
