// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Schema.Handoff
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Additional channel specific context
    /// </summary>
    public partial class HandoffParameters
    {
        /// <summary>
        /// Initializes a new instance of the HandoffParameters class.
        /// </summary>
        public HandoffParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HandoffParameters class.
        /// </summary>
        /// <param name="transcript">Activities so far.</param>
        /// <param name="handoffContext">Channel specific payload for creating
        /// the conversation</param>
        public HandoffParameters(Transcript transcript, object handoffContext = default(object))
        {
            Transcript = transcript;
            HandoffContext = handoffContext;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets activities so far.
        /// </summary>
        [JsonProperty(PropertyName = "transcript")]
        public Transcript Transcript { get; set; }

        /// <summary>
        /// Gets or sets channel specific payload for creating the conversation
        /// </summary>
        [JsonProperty(PropertyName = "handoffContext")]
        public object HandoffContext { get; set; }

    }
}
