/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from '@azure/ms-rest-js';

export const teamId: msRest.OperationURLParameter = {
  parameterPath: 'teamId',
  mapper: {
    required: true,
    serializedName: 'teamId',
    type: {
      name: 'String'
    }
  }
};
