//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskModuleFactorySample.Tests.Utterances
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralUtterances
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralUtterances()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskModuleFactorySample.Tests.Utterances.GeneralUtterances", typeof(GeneralUtterances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cancel it.
        /// </summary>
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Confirm
        {
            get
            {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to can i talk to a person.
        /// </summary>
        internal static string Escalate
        {
            get
            {
                return ResourceManager.GetString("Escalate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to all finished.
        /// </summary>
        internal static string FinishTask
        {
            get
            {
                return ResourceManager.GetString("FinishTask", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        internal static string GoBack
        {
            get
            {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Help
        {
            get
            {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string None
        {
            get
            {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string Reject
        {
            get
            {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to could you say it again.
        /// </summary>
        internal static string Repeat
        {
            get
            {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to any one is ok.
        /// </summary>
        internal static string SelectAny
        {
            get
            {
                return ResourceManager.GetString("SelectAny", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to choose the last one.
        /// </summary>
        internal static string SelectItem
        {
            get
            {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to none of them.
        /// </summary>
        internal static string SelectNone
        {
            get
            {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string ShowNext
        {
            get
            {
                return ResourceManager.GetString("ShowNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        internal static string ShowPrevious
        {
            get
            {
                return ResourceManager.GetString("ShowPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        internal static string StartOver
        {
            get
            {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to be quiet.
        /// </summary>
        internal static string Stop
        {
            get
            {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
    }
}
