//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollerSkillBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RollerSkillBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ouch|I hope your luck improves.|I think I saw that coming.|That&apos;s not good..
        /// </summary>
        internal static string BadRollReactionSSML {
            get {
                return ResourceManager.GetString("BadRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was a perfect roll!|Awesome!|You can&apos;t get better than that..
        /// </summary>
        internal static string BestRollReactionSSML {
            get {
                return ResourceManager.GetString("BestRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rolled {0} dice using a {1}-sided dice.
        /// </summary>
        internal static string CardSubtitlePlural {
            get {
                return ResourceManager.GetString("CardSubtitlePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using a {1}-sided dice.
        /// </summary>
        internal static string CardSubtitleSingular {
            get {
                return ResourceManager.GetString("CardSubtitleSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many {0} sided dice should I roll?.
        /// </summary>
        internal static string ChooseCount {
            get {
                return ResourceManager.GetString("ChooseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many dice? Choose a number from 1 to a hundred.|How many dice? The more the merrier|How many dice?.
        /// </summary>
        internal static string ChooseCountSSML {
            get {
                return ResourceManager.GetString("ChooseCountSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sides.
        /// </summary>
        internal static string ChooseSides {
            get {
                return ResourceManager.GetString("ChooseSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many sides on the dice?|Pick your poison.|All the standard sizes are supported..
        /// </summary>
        internal static string ChooseSidesSSML {
            get {
                return ResourceManager.GetString("ChooseSidesSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice, an eleven you win!.
        /// </summary>
        internal static string CrapsElevenRollReactionSSML {
            get {
                return ResourceManager.GetString("CrapsElevenRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You crapped out.|Oh no you lost..
        /// </summary>
        internal static string CrapsLoseRollReactionSSML {
            get {
                return ResourceManager.GetString("CrapsLoseRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll again.|Try again you want a seven or eleven.|Roll again and try not to get a 2, 3, or 12..
        /// </summary>
        internal static string CrapsRetryRollReactionSSML {
            get {
                return ResourceManager.GetString("CrapsRetryRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win with a lucky seven!.
        /// </summary>
        internal static string CrapsSevenRollReactionSSML {
            get {
                return ResourceManager.GetString("CrapsSevenRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s pretty good.|There you go.|That should help..
        /// </summary>
        internal static string GoodRollReactionSSML {
            get {
                return ResourceManager.GetString("GoodRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m roller, the dice rolling bot. You can say &apos;roll some dice&apos; or play one of the games I know how to play..
        /// </summary>
        internal static string HelpSSML {
            get {
                return ResourceManager.GetString("HelpSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller Options.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not too bad|It could have been worse.|That was a decent roll..
        /// </summary>
        internal static string NormalRollReactionSSML {
            get {
                return ResourceManager.GetString("NormalRollReactionSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love vegas.|Good luck..
        /// </summary>
        internal static string StartCrapsGameSSML {
            get {
                return ResourceManager.GetString("StartCrapsGameSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets do this!|Here we go.|Are you ready for this?.
        /// </summary>
        internal static string StartCustomGameSSML {
            get {
                return ResourceManager.GetString("StartCustomGameSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wow... just wow...|oh no. That was horrible.| You can&apos;t do better. Oh wait you can..
        /// </summary>
        internal static string WorstRollReactionSSML {
            get {
                return ResourceManager.GetString("WorstRollReactionSSML", resourceCulture);
            }
        }
    }
}
