//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoFlowers.BotAssets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContosoFlowers.BotAssets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string AddressDialog_Confirm {
            get {
                return ResourceManager.GetString("AddressDialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean?.
        /// </summary>
        internal static string AddressDialog_DidYouMean {
            get {
                return ResourceManager.GetString("AddressDialog_DidYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string AddressDialog_Edit {
            get {
                return ResourceManager.GetString("AddressDialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not understand that address. Can you try again? (Number, street, city, state, and ZIP).
        /// </summary>
        internal static string AddressDialog_EnterAddressAgain {
            get {
                return ResourceManager.GetString("AddressDialog_EnterAddressAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this address.
        /// </summary>
        internal static string AddressDialog_UseThisAddress {
            get {
                return ResourceManager.GetString("AddressDialog_UseThisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can type Cancel or (B)ack or Abort to abandon this dialog..
        /// </summary>
        internal static string CancelablePromptChoice_CancelText {
            get {
                return ResourceManager.GetString("CancelablePromptChoice_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, you want to use {0}. Is that correct? Enter &apos;yes&apos; or &apos;no&apos;..
        /// </summary>
        internal static string Location_ConfirmationAsk {
            get {
                return ResourceManager.GetString("Location_ConfirmationAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item.
        /// </summary>
        internal static string PagedCarouselDialog_DefaultPrompt {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_DefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want more options?.
        /// </summary>
        internal static string PagedCarouselDialog_MoreOptions {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, please!.
        /// </summary>
        internal static string PagedCarouselDialog_ShowMe {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_ShowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not understand that email address. Can you try again?.
        /// </summary>
        internal static string PromptEmail_DefaultRetry {
            get {
                return ResourceManager.GetString("PromptEmail_DefaultRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new address.
        /// </summary>
        internal static string SavedAddressDialog_AddNewAddress {
            get {
                return ResourceManager.GetString("SavedAddressDialog_AddNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks!.
        /// </summary>
        internal static string SavedAddressDialog_NotThisTime {
            get {
                return ResourceManager.GetString("SavedAddressDialog_NotThisTime", resourceCulture);
            }
        }
    }
}
