# specific branch build
trigger:
  branches:  
    include:
    - master
    - feature/*
  
pool:
   name: Hosted VS2017
   demands:
    - msbuild
    - visualstudio

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.100'
  inputs:
    version: 2.2.100
  continueOnError: true

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.1'
  inputs:
    versionSpec: 4.9.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    # if your working directory is not root, you may change the following path
    restoreSolution: 'LivePersonProxyAssistant.sln'

- task: VSBuild@1
  displayName: 'Build solution LivePersonProxyAssistant.sln'
  inputs:
    # if your working directory is not root, you may change the following path
    solution: LivePersonProxyAssistant.sln
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'test results'
  inputs:
    command: test
    # if your working directory is not root, you may change the following path
    projects: '$(System.DefaultWorkingDirectory)\LivePersonProxyAssistant.Tests.csproj'
    arguments: '-v n --configuration $(buildConfiguration) --no-build --no-restore --filter TestCategory!=IgnoreInAutomatedBuild /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    # if your working directory is not root, you may change the following path
    workingDirectory: 'LivePersonProxyAssistant.Tests'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    # if your working directory is not root, you may change the following path
    summaryFileLocation: '$(Build.SourcesDirectory)\LivePersonProxyAssistant.Tests\coverage.cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)\LivePersonProxyAssistant.Tests'

 - task: CopyFiles@2
  displayName: 'Copy VA'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\templates\Virtual-Assistant-Template\csharp\Sample\VirtualAssistantSample'
    Contents: '**\*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\VA'

- task: PublishBuildArtifacts@1
  displayName: 'Artifacts'