//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentsBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this item can be shipped to your selected address..
        /// </summary>
        internal static string RootDialog_Invalid_Address {
            get {
                return ResourceManager.GetString("RootDialog_Invalid_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid purchase, please try again...
        /// </summary>
        internal static string RootDialog_Invalid_Purchase {
            get {
                return ResourceManager.GetString("RootDialog_Invalid_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string RootDialog_Receipt_OrderID {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string RootDialog_Receipt_PaymentMethod {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order **#{0}** has been processed! Your payment has been confirmed by **{1}**. 
        ///Thank you for using Contoso Red T-Shirts. 
        ///Here is your receipt:.
        /// </summary>
        internal static string RootDialog_Receipt_Text {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso Red T-Shirts Receipt.
        /// </summary>
        internal static string RootDialog_Receipt_Title {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string RootDialog_Shipping_Address {
            get {
                return ResourceManager.GetString("RootDialog_Shipping_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Option.
        /// </summary>
        internal static string RootDialog_Shipping_Option {
            get {
                return ResourceManager.GetString("RootDialog_Shipping_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome **{0}** to Contoso Red T-Shirts, here you can only buy Scott Gu - Favorite Shirts.
        /// </summary>
        internal static string RootDialog_Welcome_Msg {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Wallet_Label_Shipping {
            get {
                return ResourceManager.GetString("Wallet_Label_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        internal static string Wallet_Label_Tax {
            get {
                return ResourceManager.GetString("Wallet_Label_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Wallet_Label_Total {
            get {
                return ResourceManager.GetString("Wallet_Label_Total", resourceCulture);
            }
        }
    }
}
